source "https://api.berkshelf.com/"

cookbook 'yum'
cookbook 'vim'
cookbook 'openssl', '~> 2.0.0'
cookbook 'nginx'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'ruby_build'
cookbook 'mongodb', github: 'edelight/chef-mongodb'
